package entities;
// Generated Aug 7, 2022 9:12:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="supermarketdb"
)
public class Category  implements java.io.Serializable {


     private String catId;
     private String catName;
     private String catDesc;

    public Category() {
    }

    public Category(String catId, String catName, String catDesc) {
       this.catId = catId;
       this.catName = catName;
       this.catDesc = catDesc;
    }
   
     @Id 

    
    @Column(name="CatId", unique=true, nullable=false)
    public String getCatId() {
        return this.catId;
    }
    
    public void setCatId(String catId) {
        this.catId = catId; 
    }

    
    @Column(name="CatName", nullable=false, length=20)
    public String getCatName() {
        return this.catName;
    }
    
    public void setCatName(String catName) {
        this.catName = catName;
    }

    
    @Column(name="CatDesc", nullable=false, length=30)
    public String getCatDesc() {
        return this.catDesc;
    }
    
    public void setCatDesc(String catDesc) {
        this.catDesc = catDesc;
    }




}


